### ISSUE TITLE
Remove leveling from Viki menus 

### ISSUE THREAD

**Issue by larsbrubaker** [MatterHackers/PulseV1Firmware#21]
![image.png](https://images.zenhubusercontent.com/57462a6ebf93871ccd9b9d98/6fa1fe15-f530-4b32-8a2c-751cb6a1c0cc)

![image.png](https://images.zenhubusercontent.com/57462a6ebf93871ccd9b9d98/1bcd9bb4-b944-4bdf-9c36-2cb90d0606df)

**Comment by RSteel517** [comment]
Just curious, why was this removed?  Other printers (Ultimaker, Prusa) can do a bed leveling without being tethered to a PC.  If the Pulse is powered by Marlin firmware which support auto bed leveling, why was this removed from the Pulse?
