### ISSUE TITLE
Hardware bed leveling - kinda - improvement

### ISSUE THREAD

**Issue by martinpirringer** [MatterHackers/PulseV1Firmware#33]
Unfortunately I had to ship the Pulse a couple of times, When it arrives I did a bed level and discovered that the Points on the left side were on the map between -0.2 to -0.4 and on the far right between +3.1 and +3.4 so that means that the right Z axis screw was about 3 mm ahead of the left Z axis screw the center line was in the middle between the left and right point the front/back ususally is only off by <0.3. Nothing we can do above that probably. The software should detect that and turn either the right or left Z motor whatever steps it takes to make the Z carriage parallel to the bed. Temp - manual fix is to turn the steppers off and manually guess and slightly turn one of the screw rods until the difference is less. But that is inaccurate and time consuming. Getting the hotend carriage (x axis?) parallel to the bed also makes the Z moves smoother. Granted the bed leveling can adjust for it but I don't think running "crooked" is a good thing. I posted that here as it is specific to the Pulse or maybe any printer with a dual ball screw type Z axis movement (Prusa type?)

**Comment by larsbrubaker** [comment]
Added an issue to MatterControl for this in MatterControl. That is where we will do the work.
MatterHackers/MatterControl#4125
Add X-Axis leveling wizard
