### ISSUE TITLE
Can not set M104 B[temp] when temp is < 20 degrees from current

### ISSUE THREAD

**Issue by larsbrubaker** [MatterHackers/PulseV1Firmware#44]
We will get a thermal runaway if we set a temp more than 20 degrees below the current temp.

This is being used by the autopilot to try and get the temp lowered. I will attempt to get our B lower temp to do incremental temps so that we can get the reduction that we want.

**Comment by cope413** [comment]
need to confirm this is only occurring on Smoothie firmware

**Comment by larsbrubaker** [comment]
After discussing looks like it is only Smoothie and will not be addressed as we move to Marlin 32 bit.
